name: Build and Prettier

on: [push, pull_request]

jobs:
  test:
    name: Test on Node 12.x on Ubuntu linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn prettier
      - run: yarn build
        env:
          CI: true
